import argparse
import logging
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats

# Configure logging
logger = logging.getLogger(__name__)

# Constants
DEFAULT_PROJECT = "aging_phase2"
DEFAULT_WRK_DIR = "/mnt/labshare/raph/datasets/adrd_neuro/brain_aging/phase2"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Filter regression results based on comparison between General (LM) and Robust (RLM) models."
    )
    parser.add_argument(
        "--project",
        type=str,
        default=DEFAULT_PROJECT,
        help="Project name used for file prefixes.",
    )
    parser.add_argument(
        "--work-dir",
        type=str,
        default=DEFAULT_WRK_DIR,
        help="Base working directory.",
    )
    parser.add_argument(
        "--modality",
        type=str,
        default="rna",
        choices=["rna", "atac"],
        help="Data modality (rna or atac).",
    )
    parser.add_argument(
        "--general-type",
        type=str,
        default="wls",
        help="General regression method (e.g., wls, ols).",
    )
    parser.add_argument(
        "--robust-type",
        type=str,
        default="vwrlm",
        help="Robust regression method (e.g., vwrlm, rlm).",
    )
    parser.add_argument(
        "--max-z",
        type=float,
        default=3.0,
        help="Maximum Z-score for effect size difference outlier filtering.",
    )
    parser.add_argument("--debug", action="store_true", help="Enable debug output.")
    return parser.parse_args()


def create_pair_id(df: pd.DataFrame) -> pd.Series:
    """Create a unique identifier for feature-tissue pairs."""
    # Check for GEX-ATAC cis format
    if "endo_feature" in df.columns and "exog_feature" in df.columns:
        return df["endo_feature"] + "_" + df["exog_feature"] + "_" + df["tissue"]
    # Default age regression format
    elif "feature" in df.columns and "tissue" in df.columns:
        return df["feature"] + "_" + df["tissue"]
    else:
        raise ValueError(
            "DataFrame must contain ('feature', 'tissue') or ('endo_feature', 'exog_feature', 'tissue') columns."
        )


def main():
    args = parse_args()
    debug = args.debug

    # Setup directories
    work_dir = Path(args.work_dir)
    results_dir = work_dir / "results"
    figures_dir = work_dir / "figures"
    figures_dir.mkdir(parents=True, exist_ok=True)
    logs_dir = work_dir / "logs"

    # Configure logging
    log_filename = f"{logs_dir}/{args.modality}_filter_regression_differences.log"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[logging.FileHandler(log_filename), logging.StreamHandler()],
        force=True,
    )
    logger.info(f"Command line: {' '.join(sys.argv)}")
    logger.info(f"Logging configured. Writing to {log_filename}")

    project = args.project
    modality = args.modality.lower()
    general_type = args.general_type
    robust_type = args.robust_type

    # Define file paths
    # We expect 'all_celltypes' as generated by post_pseudobulk_regression.py
    # General input: FDR filtered results
    general_fdr_file = (
        results_dir / f"{project}.all_celltypes.{modality}.{general_type}_fdr.age.csv"
    )
    # Robust input: Full results (to be filtered by nominal p < 0.05)
    robust_file = (
        results_dir / f"{project}.all_celltypes.{modality}.{robust_type}.age.csv"
    )

    # Output file
    results_file = (
        results_dir
        / f"{project}.{modality}.all_celltypes.{general_type}_fdr_filtered.age.csv"
    )

    logger.info(f"Reading general results (LM FDR filtered) from: {general_fdr_file}")
    if not general_fdr_file.exists():
        logger.error(f"File not found: {general_fdr_file}")
        return
    general_results = pd.read_csv(general_fdr_file)
    logger.info(f"General results shape: {general_results.shape}")

    logger.info(f"Reading robust results (RLM Full) from: {robust_file}")
    if not robust_file.exists():
        logger.error(f"File not found: {robust_file}")
        return
    robust_results = pd.read_csv(robust_file)
    logger.info(f"Robust results shape: {robust_results.shape}")

    if debug:
        print("General sample:")
        print(general_results.head())
        print("Robust sample:")
        print(robust_results.head())

    # 1. Filter Robust Results (Nominal p <= 0.05)
    logger.info("Filtering robust results for p-value <= 0.05...")
    robust_results = robust_results.loc[robust_results["p-value"] <= 0.05].copy()
    logger.info(f"Robust results shape after p-value filtering: {robust_results.shape}")

    # 2. Create Pair IDs
    logger.info("Creating pair IDs...")
    general_results["pair"] = create_pair_id(general_results)
    robust_results["pair"] = create_pair_id(robust_results)

    # 3. Find Intersection
    pair_intersect = set(general_results.pair) & set(robust_results.pair)
    pct_intersect = (
        (len(pair_intersect) / general_results.shape[0]) * 100
        if general_results.shape[0] > 0
        else 0
    )
    logger.info(
        f"Intersection: {len(pair_intersect)} features found in both ({pct_intersect:.2f}%)"
    )

    # Filter general results to intersection
    filtered_results = general_results.loc[
        general_results.pair.isin(pair_intersect)
    ].copy()

    # 4. Check Direction Consistency
    logger.info("Checking effect direction consistency...")
    merged = filtered_results.merge(
        robust_results[["pair", "coef"]],
        on="pair",
        how="left",
        suffixes=(f"_{general_type}", f"_{robust_type}"),
    )

    # Renaming for clarity based on suffix addition if cols existed,
    # but robust_results was sliced to just pair and coef.
    # General results likely has 'coef'.
    # So merge gives 'coef_{general_type}' and 'coef_{robust_type}'.

    coef_gen_col = f"coef_{general_type}"
    coef_rob_col = f"coef_{robust_type}"

    # Identify retained pairs (same direction)
    consistent_mask = (merged[coef_gen_col] * merged[coef_rob_col]) >= 0
    kept_pairs = merged.loc[consistent_mask, "pair"]

    logger.info(
        f"Features with consistent direction: {len(kept_pairs)} out of {len(merged)}"
    )

    # Filter
    filtered_results = filtered_results.loc[
        filtered_results.pair.isin(kept_pairs)
    ].copy()
    # Also update 'merged' (which we use for Z-score next) to only include kept rows
    kept_merged = merged.loc[consistent_mask].copy()

    # 5. Outlier Filtering (Z-score of effect delta)
    logger.info(f"Filtering effect size outliers (Max Z = {args.max_z})...")
    kept_merged["effect_delta"] = kept_merged[coef_gen_col] - kept_merged[coef_rob_col]
    kept_merged["effect_delta_z"] = stats.zscore(kept_merged["effect_delta"])

    # Plot distribution
    plt.figure(figsize=(10, 6))
    sns.histplot(kept_merged["effect_delta_z"], kde=True)
    plt.title(f"Distribution of Effect Delta Z-scores ({modality})")
    plt.xlabel("Z-score of (Coef LM - Coef RLM)")
    fig_path = figures_dir / f"{project}.{modality}.effect_delta_z_distribution.png"
    plt.savefig(fig_path)
    plt.close()
    logger.info(f"Saved Z-score distribution plot to {fig_path}")

    # Apply filter
    z_mask = kept_merged["effect_delta_z"].abs() < args.max_z
    final_pairs = kept_merged.loc[z_mask, "pair"]

    n_outliers = (~z_mask).sum()
    logger.info(f"Removed {n_outliers} outliers based on Z-score.")

    final_results = filtered_results.loc[filtered_results.pair.isin(final_pairs)].copy()

    # 6. Save
    logger.info(f"Final filtered results shape: {final_results.shape}")

    # Drop the 'pair' column before saving to match original structure
    final_results = final_results.drop(columns=["pair"])

    logger.info(f"Saving results to {results_file}")
    final_results.to_csv(results_file, index=False)

    # Summary of counts per cell type
    total_counts = general_results["tissue"].value_counts()
    sig_counts = final_results["tissue"].value_counts()

    summary_df = pd.DataFrame({"Total": total_counts, "Retained": sig_counts})
    summary_df["Retained"] = summary_df["Retained"].fillna(0).astype(int)
    summary_df["Percentage"] = (
        summary_df["Retained"] / summary_df["Total"] * 100
    ).round(2)
    summary_df = summary_df.sort_values("Percentage", ascending=False)

    logger.info("Summary of filtered results per cell type:")
    logger.info(summary_df.sort_index())


if __name__ == "__main__":
    main()
