import os
import sys
import tempfile
import unittest
import numpy as np
import pandas as pd
import anndata as ad
import mudata as md
from subprocess import run


class TestDiseaseDataPrep(unittest.TestCase):
    def setUp(self):
        # Create temp directory
        self.test_dir = tempfile.TemporaryDirectory()
        
        # We need a reasonable number of cells (e.g. 60 cells across 3 donors)
        # 20 cells per donor
        donors = ["donor_1"] * 20 + ["donor_2"] * 20 + ["donor_3"] * 20
        obs_index = [f"cell_{i}" for i in range(60)]
        
        # Mock some covariates, including 'diagnosis'
        diagnosis_strings = (
            ["control,no cognitive impairment"] * 20 +
            ["Alzheimer disease,dementia"] * 20 +
            ["Other diagnosis"] * 20 # Will be mapped to NaN
        )
        
        # Categorical and continuous covariates
        sex = ["M"] * 30 + ["F"] * 30
        race = ["Caucasian"] * 30 + ["African American"] * 30
        
        # Test '90+' replacement by making the first cells of donor_1 '90+'
        ageDeath = np.random.uniform(70, 89, size=60).tolist()
        ageDeath = [str(x) for x in ageDeath]
        for i in range(20):
            ageDeath[i] = "90+"
            
        PMI = np.random.uniform(4, 12, size=60).tolist()
        pH = np.random.uniform(6.0, 7.0, size=60).tolist()
        brainWeight = np.random.uniform(1100, 1400, size=60).tolist()
        
        # Create dummy AnnData objects
        rna_data = ad.AnnData(
            X=np.random.randint(10, 100, size=(60, 10)).astype(np.float32),
            obs=pd.DataFrame({
                "sample_id": donors,
                "broad_cell_type": ["Neuron"] * 30 + ["Astrocyte"] * 30,
                "diagnosis": diagnosis_strings,
                "sex": sex,
                "race": race,
                "ageDeath": ageDeath,
                "PMI": PMI,
                "pH": pH,
                "brainWeight": brainWeight
            }, index=obs_index),
            var=pd.DataFrame(index=[f"gene_{i}" for i in range(10)])
        )
        
        atac_data = ad.AnnData(
            X=np.random.randint(0, 10, size=(60, 15)).astype(np.float32),
            obs=pd.DataFrame({
                "sample_id": donors,
                "broad_cell_type": ["Neuron"] * 30 + ["Astrocyte"] * 30,
                "diagnosis": diagnosis_strings,
                "sex": sex,
                "race": race,
                "ageDeath": ageDeath,
                "PMI": PMI,
                "pH": pH,
                "brainWeight": brainWeight
            }, index=obs_index),
            var=pd.DataFrame(index=[f"peak_{i}" for i in range(15)])
        )
        
        # Create MuData object
        self.mdata = md.MuData({"rna": rna_data, "atac": atac_data})
        self.mdata_path = os.path.join(self.test_dir.name, "test_input.h5mu")
        self.mdata.write(self.mdata_path)
        
        # Create info_dir and quants_dir
        self.info_dir = os.path.join(self.test_dir.name, "sample_info")
        self.quants_dir = os.path.join(self.test_dir.name, "quants")
        os.makedirs(self.info_dir, exist_ok=True)
        os.makedirs(self.quants_dir, exist_ok=True)
        
        # Write mock quantified parquets for the 'Neuron' cell type
        # In a real workflow, this would be generated by pseudobulk_convert.py
        self.neuron_rna_parquet = os.path.join(self.quants_dir, "test_project.Neuron.rna.parquet")
        self.neuron_atac_parquet = os.path.join(self.quants_dir, "test_project.Neuron.atac.parquet")
        
        # Neuron samples are present in donor_1 (Control) and donor_2 (AD)
        # donor_3 (Other) is present, but will be dropped in prep_pb_data.py because dx is NaN
        pd.DataFrame(
            np.random.rand(3, 10).astype(np.float32),
            index=["donor_1", "donor_2", "donor_3"],
            columns=[f"gene_{i}" for i in range(10)]
        ).to_parquet(self.neuron_rna_parquet)
        
        pd.DataFrame(
            np.random.rand(3, 15).astype(np.float32),
            index=["donor_1", "donor_2", "donor_3"],
            columns=[f"peak_{i}" for i in range(15)]
        ).to_parquet(self.neuron_atac_parquet)
        
    def tearDown(self):
        self.test_dir.cleanup()
        
    def test_pipeline_data_prep(self):
        # 1. Run format_covariates.py
        cmd_format = [
            sys.executable,
            "phase2/development/SEAAD/analyses/format_covariates.py",
            "-i", self.mdata_path,
            "--project", "test_project",
            "--work-dir", self.test_dir.name,
            "--cell-type-col", "broad_cell_type",
            "--sample-col", "sample_id",
        ]
        res_format = run(cmd_format, capture_output=True, text=True)
        self.assertEqual(res_format.returncode, 0, f"format_covariates failed:\n{res_format.stderr}\n{res_format.stdout}")
        
        # Verify covariates exist
        expected_covar_files = [
            "test_project.covariates.rna.csv",
            "test_project.covariates.atac.csv",
        ]
        for fname in expected_covar_files:
            fpath = os.path.join(self.info_dir, fname)
            self.assertTrue(os.path.exists(fpath))
            
            # Read and verify content
            df = pd.read_csv(fpath, index_col=0)
            
            # Index should be sample_id / donor names
            self.assertIn("donor_1", df.index)
            self.assertIn("donor_2", df.index)
            self.assertIn("donor_3", df.index)
            
            # Should have the new 'dx' column with correct engineered values
            self.assertEqual(df.loc["donor_1", "dx"], 0.0) # Control
            self.assertEqual(df.loc["donor_2", "dx"], 1.0) # AD
            self.assertTrue(pd.isna(df.loc["donor_3", "dx"])) # Other should be NaN
            
            # Verify '90+' was correctly replaced with a random value in range [91.0, 96.0]
            val = df.loc["donor_1", "ageDeath"]
            self.assertGreaterEqual(val, 91.0)
            self.assertLessEqual(val, 96.0)
            
            # Should contain all our requested covariates
            self.assertIn("sex", df.columns)
            self.assertIn("race", df.columns)
            self.assertIn("ageDeath", df.columns)
            self.assertIn("PMI", df.columns)
            self.assertIn("pH", df.columns)
            self.assertIn("brainWeight", df.columns)
            
            # Should contain the pivoted cell count column
            self.assertIn("Neuron_counts", df.columns)
            self.assertIn("Astrocyte_counts", df.columns)

        # 2. Run prep_pb_data.py for Neuron cell type on GEX (rna) modality
        cmd_prep = [
            sys.executable,
            "phase2/development/SEAAD/analyses/prep_pb_data.py",
            "--project", "test_project",
            "--work-dir", self.test_dir.name,
            "--modality", "rna",
            "--cell-type", "Neuron",
            "--target-variable", "dx",
            "--top-var-fraction", "0.50", # Larger fraction to ensure we capture enough features in mock data
        ]
        res_prep = run(cmd_prep, capture_output=True, text=True)
        self.assertEqual(res_prep.returncode, 0, f"prep_pb_data failed:\n{res_prep.stderr}\n{res_prep.stdout}")
        
        # Verify final_covariates is created
        final_covar_file = os.path.join(self.info_dir, "test_project.Neuron.rna.final_covariates.csv")
        self.assertTrue(os.path.exists(final_covar_file))
        
        # Read and check contents of final_covariates
        final_df = pd.read_csv(final_covar_file, index_col=0)
        
        # donor_3 should have been dropped because dx is NaN
        self.assertIn("donor_1", final_df.index)
        self.assertIn("donor_2", final_df.index)
        self.assertNotIn("donor_3", final_df.index)
        
        # Rename map should have run successfully
        self.assertIn("cell_counts", final_df.columns)
        self.assertNotIn("Neuron_counts", final_df.columns)
        
        # PCA columns should have been generated and appended
        pca_cols = [c for c in final_df.columns if c.startswith("PCA_")]
        self.assertGreater(len(pca_cols), 0, "No PCA components were generated in final covariates.")
        
        # Verify residuals parquet was saved
        residuals_file = os.path.join(self.quants_dir, "test_project.Neuron.rna.residuals.parquet")
        self.assertTrue(os.path.exists(residuals_file))
        
        residuals_df = pd.read_parquet(residuals_file)
        self.assertIn("donor_1", residuals_df.index)
        self.assertNotIn("donor_3", residuals_df.index)


if __name__ == "__main__":
    unittest.main()
